### PR TITLE
Really support Symfony 5 and add Symfony 6

### PR DESCRIPTION
**Pull request by yguedidi**
A dependency of Wallabag that is not really ready for Symfony 5.
The fix is in commit [Fix on Symfony 5.x](https://github.com/wallabag/guzzle-site-authenticator/pull/34/commits/c4ff5a991471fe77c4c3c2fde296fb519c275c97).
It's temporary reverted to check if it fails properly on CI

### CODE REVIEW

**Comment by yguedidi** [comment]
@j0k3r @Kdecherf could you have a look please? 🙂

**Comment by yguedidi** [comment]
CI still need some tweaks but we can see in https://github.com/wallabag/guzzle-site-authenticator/actions/runs/5773733908/job/15652193563#step:5:117 the it wasn't working on Symfony 5

**Comment by yguedidi** [comment]
@j0k3r added a commit to fix existing CS issues, to fix the CI

**Review by Kdecherf — APPROVED** [review]
LGTM

**Review by j0k3r — APPROVED** [review]

**Comment by j0k3r** [comment]
Good job!
I'll create a release

**Pull request merged**
